<?php
/**
 * Image Download & WebP Conversion for WooCommerce Product Import
 *
 * Downloads product images from the BigCommerce CDN (as listed in the
 * WooCommerce import CSV), renames them using the product SKU, converts
 * them to WebP for ~30 % smaller file sizes, and rewrites the CSV Images
 * column to use the new local paths.
 *
 * HOSTGATOR SAFETY: processes are chunked (default 50 images per batch)
 * to prevent PHP/CPU timeouts on shared hosting.
 *
 * HOW TO USE
 * ----------
 * Option A – WP-CLI (recommended):
 *   wp eval-file wp-content/themes/drywall-toolbox/inc/image-optimizer.php
 *
 * Option B – Admin URL trigger (processes one chunk per page load):
 *   Visit /wp-admin/?dtb_image_import=1&chunk=0  (chunk=0, 1, 2 …)
 *   while logged in as admin.
 *
 * Option C – Include from functions.php and schedule with WP-Cron:
 *   add_action( 'dtb_process_image_chunk', 'dtb_process_image_chunk' );
 *   wp_schedule_single_event( time(), 'dtb_process_image_chunk', [ $offset ] );
 *
 * PREREQUISITES
 * -------------
 *  - PHP GD extension with WebP support, OR Imagick (auto-detected).
 *  - The transformed CSV must exist at public/catalog/woocommerce_products.csv
 *    (generated by scripts/transform_woocommerce_csv.py).
 *  - WordPress uploads directory must be writable.
 *
 * @package Drywall_Toolbox
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// ---------------------------------------------------------------------------
// CONFIGURATION
// ---------------------------------------------------------------------------

/** Absolute path to the WooCommerce import CSV (source + output).
 *
 * Override this constant in wp-config.php if your WordPress installation
 * is not in the default /wp subdirectory of the site root, e.g.:
 *   define( 'DTB_IMG_CSV_PATH', '/home/user/public_html/catalog/woocommerce_products.csv' );
 */
if ( ! defined( 'DTB_IMG_CSV_PATH' ) ) {
    // Resolve path relative to the WordPress uploads base directory so it
    // works regardless of the WordPress installation subdirectory.
    $dtb_uploads      = wp_upload_dir();
    $dtb_uploads_base = trailingslashit( $dtb_uploads['basedir'] );
    define(
        'DTB_IMG_CSV_PATH',
        // Walk up from uploads/ → wp-content/ → site-root/ → public/catalog/
        realpath( $dtb_uploads_base . '../../../' ) . '/public/catalog/woocommerce_products.csv'
    );
    unset( $dtb_uploads, $dtb_uploads_base );
}

/** Upload sub-directory (relative to wp-content/uploads/). */
define( 'DTB_IMG_UPLOAD_SUBDIR', '2026/03' );

/** WebP conversion quality (0-100). 82 gives ~30% smaller files vs JPEG. */
define( 'DTB_WEBP_QUALITY', 82 );

/** Number of images to process per batch (HostGator CPU safety). */
define( 'DTB_CHUNK_SIZE', 50 );

/** Progress option key stored in wp_options. */
define( 'DTB_IMG_PROGRESS_KEY', 'dtb_image_import_offset' );


// ---------------------------------------------------------------------------
// HELPERS
// ---------------------------------------------------------------------------

/**
 * Return the absolute path to the upload directory for this import.
 *
 * Creates the directory if it does not exist.
 *
 * @return string Absolute filesystem path, no trailing slash.
 */
function dtb_get_upload_dir(): string {
    $upload_base = wp_upload_dir();
    $dir = trailingslashit( $upload_base['basedir'] ) . DTB_IMG_UPLOAD_SUBDIR;
    if ( ! is_dir( $dir ) ) {
        wp_mkdir_p( $dir );
    }
    return untrailingslashit( $dir );
}

/**
 * Return the public URL prefix for the upload directory.
 *
 * @return string URL without trailing slash.
 */
function dtb_get_upload_url(): string {
    $upload_base = wp_upload_dir();
    return untrailingslashit(
        trailingslashit( $upload_base['baseurl'] ) . DTB_IMG_UPLOAD_SUBDIR
    );
}

/**
 * Sanitize a filename segment derived from a product SKU.
 *
 * Replaces characters that are unsafe in filenames with underscores.
 *
 * @param string $sku Raw SKU string.
 * @return string     Safe filename prefix.
 */
function dtb_safe_sku( string $sku ): string {
    return preg_replace( '/[^A-Za-z0-9_\-]/', '_', $sku );
}

/**
 * Extract the original filename (without query string) from a URL.
 *
 * @param string $url Image URL.
 * @return string     Original filename (e.g. "product__12345.jpg").
 */
function dtb_url_filename( string $url ): string {
    $path = parse_url( $url, PHP_URL_PATH ) ?: '';
    return basename( $path );
}

/**
 * Download a remote image URL to a local temp file.
 *
 * Uses WordPress HTTP API (wp_remote_get) for compatibility.
 *
 * @param string $url Remote image URL.
 * @return string|WP_Error Path to temp file, or WP_Error on failure.
 */
function dtb_download_image( string $url ) {
    $response = wp_remote_get(
        $url,
        [
            'timeout'  => 30,
            'stream'   => true,
            'filename' => wp_tempnam(),
        ]
    );

    if ( is_wp_error( $response ) ) {
        return $response;
    }

    $code = wp_remote_retrieve_response_code( $response );
    if ( 200 !== (int) $code ) {
        if ( ! empty( $response['filename'] ) && file_exists( $response['filename'] ) ) {
            unlink( $response['filename'] );
        }
        return new WP_Error( 'http_error', "HTTP {$code} for {$url}" );
    }

    return $response['filename'];
}

/**
 * Convert an image file to WebP and save it to the destination path.
 *
 * Tries Imagick first (better quality/speed), falls back to GD.
 *
 * @param string $source_path Absolute path to source image.
 * @param string $dest_path   Absolute path for WebP output (*.webp).
 * @return bool               True on success.
 */
function dtb_convert_to_webp( string $source_path, string $dest_path ): bool {
    // --- Try Imagick ---
    if ( class_exists( 'Imagick' ) ) {
        try {
            $imagick = new Imagick( $source_path );
            $imagick->setImageFormat( 'webp' );
            $imagick->setImageCompressionQuality( DTB_WEBP_QUALITY );
            $imagick->stripImage();
            $imagick->writeImage( $dest_path );
            $imagick->clear();
            $imagick->destroy();
            return true;
        } catch ( Exception $e ) {
            // Fall through to GD.
        }
    }

    // --- Try GD ---
    if ( function_exists( 'imagewebp' ) ) {
        $info = @getimagesize( $source_path ); // phpcs:ignore
        if ( ! $info ) {
            return false;
        }

        $mime = $info['mime'];
        $img  = null;

        switch ( $mime ) {
            case 'image/jpeg':
                $img = imagecreatefromjpeg( $source_path );
                break;
            case 'image/png':
                $img = imagecreatefrompng( $source_path );
                if ( $img ) {
                    imagealphablending( $img, false );
                    imagesavealpha( $img, true );
                }
                break;
            case 'image/gif':
                $img = imagecreatefromgif( $source_path );
                break;
            case 'image/webp':
                // Already WebP — just copy.
                return copy( $source_path, $dest_path );
        }

        if ( ! $img ) {
            return false;
        }

        $result = imagewebp( $img, $dest_path, DTB_WEBP_QUALITY );
        imagedestroy( $img );
        return $result;
    }

    // No WebP support — fall back to lossless copy with original extension.
    return copy( $source_path, $dest_path );
}

/**
 * Return true if a URL points to an already-local WordPress upload.
 *
 * @param string $url URL to test.
 * @return bool
 */
function dtb_is_local_url( string $url ): bool {
    $site_host = parse_url( get_site_url(), PHP_URL_HOST ) ?: '';
    $url_host  = parse_url( $url, PHP_URL_HOST ) ?: '';
    return $site_host === $url_host;
}


// ---------------------------------------------------------------------------
// CORE PROCESSING FUNCTION
// ---------------------------------------------------------------------------

/**
 * Process one chunk of images from the WooCommerce CSV.
 *
 * Reads the CSV, skips already-processed rows, downloads + converts images
 * for the current chunk, rewrites the Images column with local WebP paths,
 * and saves the updated CSV back to disk.
 *
 * @param int $offset Row offset (0-based, excluding header). Defaults to the
 *                    last saved progress value from wp_options.
 */
function dtb_process_image_chunk( int $offset = -1 ): void {
    $csv_path = DTB_IMG_CSV_PATH;

    if ( ! file_exists( $csv_path ) ) {
        dtb_log( "CSV not found: {$csv_path}" );
        return;
    }

    if ( $offset < 0 ) {
        $offset = (int) get_option( DTB_IMG_PROGRESS_KEY, 0 );
    }

    $upload_dir = dtb_get_upload_dir();
    $upload_url = dtb_get_upload_url();

    // Load full CSV into memory (file is typically < 5 MB).
    $rows   = [];
    $header = [];

    $handle = fopen( $csv_path, 'r' );
    if ( ! $handle ) {
        dtb_log( "Cannot open CSV: {$csv_path}" );
        return;
    }

    $header = fgetcsv( $handle );
    if ( ! $header ) {
        fclose( $handle );
        dtb_log( 'CSV has no header row.' );
        return;
    }

    while ( ( $row = fgetcsv( $handle ) ) !== false ) {
        $rows[] = $row;
    }
    fclose( $handle );

    $images_col = array_search( 'Images', $header, true );
    $sku_col    = array_search( 'SKU', $header, true );
    $type_col   = array_search( 'Type', $header, true );

    if ( false === $images_col || false === $sku_col ) {
        dtb_log( 'CSV missing required columns (SKU, Images).' );
        return;
    }

    $total    = count( $rows );
    $end      = min( $offset + DTB_CHUNK_SIZE, $total );
    $modified = 0;

    for ( $i = $offset; $i < $end; $i++ ) {
        $row  = $rows[ $i ];
        $sku  = isset( $row[ $sku_col ] ) ? trim( $row[ $sku_col ] ) : '';
        $type = isset( $row[ $type_col ] ) ? strtolower( trim( $row[ $type_col ] ) ) : 'simple';

        // Skip variation rows without a meaningful name — they share parent images.
        if ( 'variation' === $type && empty( $sku ) ) {
            continue;
        }

        $images_raw = isset( $row[ $images_col ] ) ? trim( $row[ $images_col ] ) : '';
        if ( empty( $images_raw ) ) {
            continue;
        }

        $image_urls   = array_filter( array_map( 'trim', explode( ',', $images_raw ) ) );
        $local_paths  = [];
        $img_index    = 1;

        foreach ( $image_urls as $url ) {
            if ( dtb_is_local_url( $url ) ) {
                // Already a local URL — keep as-is.
                $local_paths[] = $url;
                $img_index++;
                continue;
            }

            $safe_sku  = dtb_safe_sku( $sku );
            $orig_name = dtb_url_filename( $url );
            $ext       = strtolower( pathinfo( $orig_name, PATHINFO_EXTENSION ) ) ?: 'jpg';

            // Destination filename: {SKU}_{index}.webp
            $dest_filename = sprintf( '%s_%02d.webp', $safe_sku, $img_index );
            $dest_path     = $upload_dir . '/' . $dest_filename;
            $dest_url      = $upload_url . '/' . $dest_filename;

            // Skip if already downloaded.
            if ( file_exists( $dest_path ) ) {
                $local_paths[] = $dest_url;
                $img_index++;
                continue;
            }

            $temp_file = dtb_download_image( $url );
            if ( is_wp_error( $temp_file ) ) {
                dtb_log( "Download failed for {$url}: " . $temp_file->get_error_message() );
                $local_paths[] = $url; // Keep original URL as fallback.
                $img_index++;
                continue;
            }

            if ( dtb_convert_to_webp( $temp_file, $dest_path ) ) {
                $local_paths[] = $dest_url;
                dtb_log( "Saved: {$dest_filename}" );
                $modified++;
            } else {
                // WebP failed — keep original extension.
                $fallback_filename = sprintf( '%s_%02d.%s', $safe_sku, $img_index, $ext );
                $fallback_path     = $upload_dir . '/' . $fallback_filename;
                rename( $temp_file, $fallback_path );
                $local_paths[] = $upload_url . '/' . $fallback_filename;
                dtb_log( "Saved (no WebP): {$fallback_filename}" );
                $modified++;
            }

            if ( file_exists( $temp_file ) ) {
                unlink( $temp_file );
            }
            $img_index++;
        }

        $rows[ $i ][ $images_col ] = implode( ',', $local_paths );
    }

    // Rewrite CSV only if something changed.
    if ( $modified > 0 ) {
        $tmp_path = $csv_path . '.tmp';
        $out      = fopen( $tmp_path, 'w' );
        if ( $out ) {
            fputcsv( $out, $header );
            foreach ( $rows as $row ) {
                fputcsv( $out, $row );
            }
            fclose( $out );
            rename( $tmp_path, $csv_path );
        }
    }

    // Advance progress pointer.
    $next_offset = $end;
    update_option( DTB_IMG_PROGRESS_KEY, $next_offset );

    $remaining = $total - $next_offset;
    dtb_log( "Chunk done. Offset {$offset}→{$next_offset}. Remaining: {$remaining} rows. Modified: {$modified} images." );

    if ( $next_offset < $total ) {
        dtb_log( "Schedule next chunk (offset {$next_offset}) or re-run with chunk={$next_offset}." );
    } else {
        dtb_log( 'All chunks processed. Image import complete.' );
        delete_option( DTB_IMG_PROGRESS_KEY );
    }
}

/**
 * Simple logger — uses WP_CLI::log() when available, error_log() otherwise.
 *
 * @param string $message Log message.
 */
function dtb_log( string $message ): void {
    if ( defined( 'WP_CLI' ) && WP_CLI ) {
        WP_CLI::log( '[DTB Image] ' . $message );
    } else {
        error_log( '[DTB Image] ' . $message );
    }
}


// ---------------------------------------------------------------------------
// TRIGGERS
// ---------------------------------------------------------------------------

// Admin URL trigger: /wp-admin/?dtb_image_import=1[&chunk=N]
add_action( 'admin_init', function () {
    if (
        isset( $_GET['dtb_image_import'] ) // phpcs:ignore WordPress.Security.NonceVerification
        && current_user_can( 'manage_woocommerce' )
    ) {
        $chunk_offset = isset( $_GET['chunk'] ) ? (int) $_GET['chunk'] : -1; // phpcs:ignore WordPress.Security.NonceVerification
        dtb_process_image_chunk( $chunk_offset );
        wp_die( 'Image chunk processed. Check error_log for details.' );
    }
} );

// WP-CLI: run immediately when evaluated directly.
if ( defined( 'WP_CLI' ) && WP_CLI ) {
    dtb_process_image_chunk( 0 );
}
