export default function SummaryView({ data }) {
  const { sheets, mud, tape, bead, screws, projectName } = data

  const exportEstimate = () => {
    const date = new Date().toLocaleDateString()
    let text = `DRYWALL MATERIAL ESTIMATE\n`
    text += `Project: ${projectName || 'New Project'}\n`
    text += `Date: ${date}\n`
    text += `${'='.repeat(50)}\n\n`
    text += `DRYWALL SHEETS\n`
    text += `  Quantity: ${sheets.sheets} sheets\n`
    text += `  Size: ${sheetSizeLabels[sheets.sheetSize] || '—'}\n`
    text += `  Direction: ${sheets.hangDir === 'horizontal' ? 'Horizontal' : 'Vertical'}\n`
    text += `  Wall Area: ${sheets.wallArea || sheets.gross} sq ft\n`
    text += `  Ceiling Area: ${sheets.ceilArea || 0} sq ft\n`
    text += `  Base Sheets (no waste): ${sheets.baseSheets ?? '—'}\n`
    text += `  Dynamic Waste: ${sheets.dynamicWaste != null ? Math.round(sheets.dynamicWaste * 100) + '%' : '—'} (${sheets.totalVerticalSeams ?? 0} vertical seams)\n`
    text += `  Applied Waste: ${sheets.wastePct != null ? Math.round(sheets.wastePct * 100) + '%' : '—'}\n`
    text += `  Total Joint Footage: ${sheets.totalJointLinearFeet ?? '—'} lf\n\n`
    text += `JOINT COMPOUND (MUD)\n`
    text += `  Total: ${mud.totalGallons} gallons\n`
    text += `  Finish Level: ${mud.finishLevel !== undefined ? `Level ${mud.finishLevel}` : '—'}\n`
    text += `  Compound Type: ${mud.compoundType || '—'}\n`
    text += `  5-gal buckets: ${mud.buckets5gal}\n\n`
    text += `JOINT TAPE\n`
    text += `  Quantity: ${tape.rolls} rolls\n`
    text += `  Type: ${tape.tapeType === 'paper' ? 'Paper tape' : tape.tapeType === 'mesh' ? 'Fiberglass mesh' : 'Flexible corner'}\n`
    text += `  Roll Size: ${tape.rollSize} ft\n`
    text += `  Total Footage: ${tape.totalFeet} ft\n\n`
    text += `CORNER BEAD\n`
    text += `  Quantity: ${bead.sections} sections\n`
    text += `  Type: ${bead.beadType}\n`
    text += `  Stock Length: ${bead.stockLength} ft\n`
    text += `  Total Footage: ${bead.totalFeet} ft\n\n`
    text += `DRYWALL SCREWS\n`
    text += `  Quantity: ${screws.boxes} boxes\n`
    text += `  Length: ${screws.screwLength}\n`
    text += `  Box Size: ${screws.boxSize} screws\n`
    text += `  Total Screws: ${screws.totalScrews}\n\n`
    text += `${'='.repeat(50)}\n`
    text += `Generated by Drywall Toolbox Calculator\n`
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${(projectName || 'estimate').replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const shareEstimate = () => {
    const url = window.location.href
    if (navigator.clipboard) {
      navigator.clipboard.writeText(url).then(() => {
        alert('Share link copied to clipboard!')
      }).catch(() => {
        prompt('Copy this link to share:', url)
      })
    } else {
      prompt('Copy this link to share:', url)
    }
  }

  const sheetSizeLabels = { 32: '4×8 ft', 48: '4×12 ft', 54: '4×13.5 ft' }
  const hangDirLabels = { horizontal: 'Horizontal', vertical: 'Vertical' }
  const tapeTypeLabels = { paper: 'Paper tape', mesh: 'Fiberglass mesh', flex: 'Flexible corner' }
  const beadTypeLabels = { standard: 'Standard metal', bullnose: 'Bullnose', vinyl: 'Vinyl', flex: 'Flexible/arch' }
  const appLabels = { wall: 'Walls', ceiling: 'Ceiling', both: 'Walls + Ceiling' }

  return (
    <div className="space-y-4">

      {/* Sheets */}
      <SummaryCard
        title="Drywall Sheets"
        result={`${sheets.sheets || '—'} sheets`}
      >
        <SummaryItem label="Sheet size"                value={sheetSizeLabels[sheets.sheetSize] || '—'} />
        <SummaryItem label="Hang direction"            value={hangDirLabels[sheets.hangDir] || '—'} />
        <SummaryItem label="Total wall area"           value={`${sheets.gross || '—'} sq ft`} />
        <SummaryItem label="Net area (after openings)" value={`${sheets.net || '—'} sq ft`} />
        <SummaryItem label="Base sheets (no waste)"    value={sheets.baseSheets != null ? sheets.baseSheets : '—'} />
        <SummaryItem
          label="Dynamic waste"
          value={sheets.dynamicWaste != null ? `${Math.round(sheets.dynamicWaste * 100)}% (${sheets.totalVerticalSeams ?? 0} v-seams)` : '—'}
        />
        <SummaryItem
          label="Applied waste factor"
          value={sheets.wastePct != null ? `${(sheets.wastePct * 100).toFixed(0)}%` : '—'}
        />
        <SummaryItem
          label="Total joint footage"
          value={sheets.totalJointLinearFeet != null ? `${sheets.totalJointLinearFeet} lf` : '—'}
        />
      </SummaryCard>

      {/* Tape */}
      <SummaryCard
        title="Joint Tape"
        result={`${tape.rolls || '—'} rolls`}
      >
        <SummaryItem label="Tape type"        value={tapeTypeLabels[tape.tapeType] || '—'} />
        <SummaryItem label="Roll size"        value={`${tape.rollSize || '—'} ft`} />
        <SummaryItem label="Total linear feet" value={`${tape.totalFeet || '—'} ft`} />
        <SummaryItem label="Joint footage"    value={tape.syncedFromSheets ? `${tape.seamFeet || '—'} ft (layout)` : `${tape.seamFeet || '—'} ft (est.)`} />
        <SummaryItem label="Corner footage"   value={`${tape.cornerFeet || '—'} ft`} />
      </SummaryCard>

      {/* Corner Bead */}
      <SummaryCard
        title="Corner Bead"
        result={`${bead.sections || '—'} sections`}
      >
        <SummaryItem label="Bead type"        value={beadTypeLabels[bead.beadType] || '—'} />
        <SummaryItem label="Stock length"     value={`${bead.stockLength || '—'} ft`} />
        <SummaryItem label="Total linear feet" value={`${bead.totalFeet || '—'} ft`} />
        <SummaryItem label="Standard corners" value={`${bead.standardFeet || '—'} ft`} />
        <SummaryItem label="Arch bead"        value={`${bead.archFeet || '—'} ft`} />
      </SummaryCard>

      {/* Screws */}
      <SummaryCard
        title="Drywall Screws"
        result={`${screws.boxes || '—'} boxes`}
      >
        <SummaryItem label="Screw length"       value={screws.screwLength || '—'} />
        <SummaryItem label="Box size"           value={`${screws.boxSize || '—'} screws`} />
        <SummaryItem label="Total screws needed" value={screws.totalScrews?.toLocaleString() || '—'} />
        <SummaryItem label="Screws per sheet"   value={screws.perSheet || '—'} />
        <SummaryItem label="Application"        value={appLabels[screws.application] || '—'} />
      </SummaryCard>

      {/* Action buttons */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-2 pt-2">
        <button
          onClick={exportEstimate}
          className="px-4 py-2.5 bg-primary-600 hover:bg-primary-700 text-white text-sm font-medium rounded-xl transition-colors"
        >
          Export Estimate
        </button>
        <button
          onClick={() => window.print()}
          className="px-4 py-2.5 bg-white hover:bg-gray-50 border border-gray-300 text-gray-700 text-sm font-medium rounded-xl transition-colors"
        >
          Print
        </button>
        <button
          onClick={shareEstimate}
          className="px-4 py-2.5 bg-white hover:bg-gray-50 border border-gray-300 text-gray-700 text-sm font-medium rounded-xl transition-colors"
        >
          Share Link
        </button>
      </div>

      {/* Disclaimer */}
      <div className="border border-primary-200 bg-primary-50 rounded-xl p-4 text-sm text-primary-800 leading-relaxed">
        All calculations are based on industry standards and IRC building codes. Always verify local code requirements and add appropriate safety margins for your specific job conditions.
      </div>

    </div>
  )
}

function SummaryCard({ title, result, children }) {
  return (
    <div className="bg-white border border-gray-200 rounded-xl overflow-hidden">
      <div className="flex justify-between items-center px-4 py-3 border-b border-gray-100">
        <h3 className="text-sm font-semibold text-gray-900">{title}</h3>
        <span className="text-sm font-semibold text-primary-600">{result}</span>
      </div>
      <div className="px-4 py-3 space-y-2">
        {children}
      </div>
    </div>
  )
}

function SummaryItem({ label, value }) {
  return (
    <div className="flex justify-between items-center text-sm">
      <span className="text-gray-500">{label}</span>
      <span className="font-medium text-gray-900">{value}</span>
    </div>
  )
}

