export default function SummaryView({ data }) {
  const { sheets, tape, bead, screws, projectName } = data

  const exportEstimate = () => {
    const date = new Date().toLocaleDateString()
    
    let text = `DRYWALL MATERIAL ESTIMATE\n`
    text += `Project: ${projectName || 'New Project'}\n`
    text += `Date: ${date}\n`
    text += `${'='.repeat(50)}\n\n`
    
    text += `DRYWALL SHEETS\n`
    text += `  Quantity: ${sheets.sheets} sheets\n`
    text += `  Size: ${sheets.sheetSize === 32 ? '4×8 ft' : sheets.sheetSize === 48 ? '4×12 ft' : '4×13.5 ft'}\n`
    text += `  Direction: ${sheets.hangDir === 'horizontal' ? 'Horizontal' : 'Vertical'}\n`
    text += `  Wall Area: ${sheets.gross} sq ft\n\n`
    
    text += `JOINT TAPE\n`
    text += `  Quantity: ${tape.rolls} rolls\n`
    text += `  Type: ${tape.tapeType === 'paper' ? 'Paper tape' : tape.tapeType === 'mesh' ? 'Fiberglass mesh' : 'Flexible corner'}\n`
    text += `  Roll Size: ${tape.rollSize} ft\n`
    text += `  Total Footage: ${tape.totalFeet} ft\n\n`
    
    text += `CORNER BEAD\n`
    text += `  Quantity: ${bead.sections} sections\n`
    text += `  Type: ${bead.beadType}\n`
    text += `  Stock Length: ${bead.stockLength} ft\n`
    text += `  Total Footage: ${bead.totalFeet} ft\n\n`
    
    text += `DRYWALL SCREWS\n`
    text += `  Quantity: ${screws.boxes} boxes\n`
    text += `  Length: ${screws.screwLength}\n`
    text += `  Box Size: ${screws.boxSize} screws\n`
    text += `  Total Screws: ${screws.totalScrews}\n\n`
    
    text += `${'='.repeat(50)}\n`
    text += `Generated by Drywall Toolbox Calculator\n`
    
    // Create download
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${(projectName || 'estimate').replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const shareEstimate = () => {
    const url = window.location.href
    if (navigator.clipboard) {
      navigator.clipboard.writeText(url).then(() => {
        alert('Share link copied to clipboard!')
      }).catch(() => {
        prompt('Copy this link to share:', url)
      })
    } else {
      prompt('Copy this link to share:', url)
    }
  }

  const sheetSizeLabels = { 32: '4×8 ft', 48: '4×12 ft', 54: '4×13.5 ft' }
  const hangDirLabels = { horizontal: 'Horizontal', vertical: 'Vertical' }
  const tapeTypeLabels = { paper: 'Paper tape', mesh: 'Fiberglass mesh', flex: 'Flexible corner' }
  const beadTypeLabels = { standard: 'Standard metal', bullnose: 'Bullnose', vinyl: 'Vinyl', flex: 'Flexible/arch' }
  const appLabels = { wall: 'Walls', ceiling: 'Ceiling', both: 'Walls + Ceiling' }

  return (
    <div className="space-y-6">
      <div className="space-y-4">
        {/* Sheets Summary */}
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
          <div className="flex justify-between items-center mb-3 pb-3 border-b border-gray-300 dark:border-gray-700">
            <span className="text-sm font-medium text-gray-900 dark:text-gray-100">
              📋 Drywall Sheets
            </span>
            <span className="text-lg font-semibold text-primary-600">
              {sheets.sheets || '—'} sheets
            </span>
          </div>
          <div className="space-y-2">
            <SummaryItem label="Sheet size" value={sheetSizeLabels[sheets.sheetSize] || '—'} />
            <SummaryItem label="Hang direction" value={hangDirLabels[sheets.hangDir] || '—'} />
            <SummaryItem label="Total wall area" value={`${sheets.gross || '—'} sq ft`} />
            <SummaryItem label="Net area (after openings)" value={`${sheets.net || '—'} sq ft`} />
            <SummaryItem label="Waste factor" value={`${(sheets.wastePct * 100).toFixed(0)}%`} />
          </div>
        </div>

        {/* Tape Summary */}
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
          <div className="flex justify-between items-center mb-3 pb-3 border-b border-gray-300 dark:border-gray-700">
            <span className="text-sm font-medium text-gray-900 dark:text-gray-100">
              📏 Joint Tape
            </span>
            <span className="text-lg font-semibold text-primary-600">
              {tape.rolls || '—'} rolls
            </span>
          </div>
          <div className="space-y-2">
            <SummaryItem label="Tape type" value={tapeTypeLabels[tape.tapeType] || '—'} />
            <SummaryItem label="Roll size" value={`${tape.rollSize || '—'} ft`} />
            <SummaryItem label="Total linear feet" value={`${tape.totalFeet || '—'} ft`} />
            <SummaryItem label="Seam footage" value={`${tape.seamFeet || '—'} ft`} />
            <SummaryItem label="Corner footage" value={`${tape.cornerFeet || '—'} ft`} />
          </div>
        </div>

        {/* Bead Summary */}
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
          <div className="flex justify-between items-center mb-3 pb-3 border-b border-gray-300 dark:border-gray-700">
            <span className="text-sm font-medium text-gray-900 dark:text-gray-100">
              📐 Corner Bead
            </span>
            <span className="text-lg font-semibold text-primary-600">
              {bead.sections || '—'} sections
            </span>
          </div>
          <div className="space-y-2">
            <SummaryItem label="Bead type" value={beadTypeLabels[bead.beadType] || '—'} />
            <SummaryItem label="Stock length" value={`${bead.stockLength || '—'} ft`} />
            <SummaryItem label="Total linear feet" value={`${bead.totalFeet || '—'} ft`} />
            <SummaryItem label="Standard corners" value={`${bead.standardFeet || '—'} ft`} />
            <SummaryItem label="Arch bead" value={`${bead.archFeet || '—'} ft`} />
          </div>
        </div>

        {/* Screws Summary */}
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
          <div className="flex justify-between items-center mb-3 pb-3 border-b border-gray-300 dark:border-gray-700">
            <span className="text-sm font-medium text-gray-900 dark:text-gray-100">
              🔩 Drywall Screws
            </span>
            <span className="text-lg font-semibold text-primary-600">
              {screws.boxes || '—'} boxes
            </span>
          </div>
          <div className="space-y-2">
            <SummaryItem label="Screw length" value={screws.screwLength || '—'} />
            <SummaryItem label="Box size" value={`${screws.boxSize || '—'} screws`} />
            <SummaryItem label="Total screws needed" value={screws.totalScrews?.toLocaleString() || '—'} />
            <SummaryItem label="Screws per sheet" value={screws.perSheet || '—'} />
            <SummaryItem label="Application" value={appLabels[screws.application] || '—'} />
          </div>
        </div>
      </div>

      {/* Action buttons */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        <button
          onClick={exportEstimate}
          className="px-4 py-3 bg-primary-600 hover:bg-primary-700 text-white font-medium rounded-md transition-colors"
        >
          📄 Export Estimate
        </button>
        <button
          onClick={() => window.print()}
          className="px-4 py-3 bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700 border border-gray-300 dark:border-gray-600 text-gray-900 dark:text-gray-100 font-medium rounded-md transition-colors"
        >
          🖨️ Print
        </button>
        <button
          onClick={shareEstimate}
          className="px-4 py-3 bg-white dark:bg-gray-800 hover:bg-gray-50 dark:hover:bg-gray-700 border border-gray-300 dark:border-gray-600 text-gray-900 dark:text-gray-100 font-medium rounded-md transition-colors"
        >
          🔗 Share Link
        </button>
      </div>

      <div className="bg-blue-50 dark:bg-blue-950 border-l-4 border-blue-500 rounded-lg p-4 text-sm text-blue-800 dark:text-blue-200">
        All calculations are based on industry standards and IRC building codes. Always verify local code requirements and add appropriate safety margins for your specific job conditions.
      </div>
    </div>
  )
}

function SummaryItem({ label, value }) {
  return (
    <div className="flex justify-between items-center text-sm">
      <span className="text-gray-600 dark:text-gray-400">{label}</span>
      <span className="font-medium text-gray-900 dark:text-gray-100">{value}</span>
    </div>
  )
}
